name: Release Pipeline

on:
  push:
    tags:
      - "v*"

jobs:
  release-pipeline:
    env:
      GITHUB_SITE_NAME: ${{ secrets.SITE_NAME_PROD }}
      GITHUB_WS_URL: ${{ secrest.WS_URL_PROD }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: Setup Configs
        run: |
          sed -i 's/GITHUB_SITE_NAME/$GITHUB_SITE_NAME/g' serverless.yml
          sed -i 's/GITHUB_WS_URL/$GITHUB_WS_URL/g' index.html
      - name: build
        run: |
          yarn
          yarn test
          yarn deploy --stage prod
